import { vi } from "vitest";
import type { Provider } from "../../src/providers/types.js";

export function createMockProvider(): Provider {
  return {
    name: "opencode" as const,
    init: vi.fn().mockResolvedValue(undefined),
    shutdown: vi.fn(),
    isAlive: vi.fn().mockResolvedValue(true),
    reconnect: vi.fn().mockResolvedValue(undefined),
    createSession: vi.fn().mockResolvedValue({ id: "sess-1", title: "Test" }),
    listSessions: vi.fn().mockResolvedValue([]),
    getSession: vi.fn().mockResolvedValue(null),
    deleteSession: vi.fn().mockResolvedValue(true),
    renameSession: vi.fn().mockResolvedValue(true),
    getSessionStatuses: vi.fn().mockResolvedValue({}),
    prompt: vi.fn().mockResolvedValue({ text: "response" }),
    abort: vi.fn().mockResolvedValue(undefined),
    promptStream: vi.fn(),
    getTodos: vi.fn().mockResolvedValue(null),
    getDiff: vi.fn().mockResolvedValue(null),
    forkSession: vi.fn().mockResolvedValue(null),
    revert: vi.fn().mockResolvedValue(false),
    unrevert: vi.fn().mockResolvedValue(false),
    share: vi.fn().mockResolvedValue(null),
    unshare: vi.fn().mockResolvedValue(false),
    summarize: vi.fn().mockResolvedValue(null),
    getHistory: vi.fn().mockResolvedValue(null),
    readFile: vi.fn().mockResolvedValue(null),
    listFiles: vi.fn().mockResolvedValue(null),
    findFiles: vi.fn().mockResolvedValue(null),
    searchText: vi.fn().mockResolvedValue(null),
    findSymbols: vi.fn().mockResolvedValue(null),
    getFileStatus: vi.fn().mockResolvedValue(null),
    shell: vi.fn().mockResolvedValue(null),
    runCommand: vi.fn().mockResolvedValue(null),
    getProjectInfo: vi.fn().mockResolvedValue(null),
    getTools: vi.fn().mockResolvedValue(null),
    getCommands: vi.fn().mockResolvedValue(null),
    getHealth: vi.fn().mockResolvedValue({ status: "ok", provider: "opencode" }),
    getPort: vi.fn().mockReturnValue(3000),
    getConfig: vi.fn().mockResolvedValue({}),
    getProviders: vi.fn().mockResolvedValue({}),
    getAgents: vi.fn().mockResolvedValue(null),
    listModels: vi.fn().mockResolvedValue([]),
    replyToQuestion: vi.fn().mockResolvedValue(undefined),
    rejectQuestion: vi.fn().mockResolvedValue(undefined),
    getMcpStatus: vi.fn().mockResolvedValue(null),
    addMcpServer: vi.fn().mockResolvedValue(true),
    removeMcpServer: vi.fn().mockResolvedValue(true),
    connectMcpServer: vi.fn().mockResolvedValue(true),
  };
}
